image: securekit-disk
config:
  binds:
    - /dev:/dev
  capabilities:
    - CAP_SYS_ADMIN
    - CAP_MKNOD
    - CAP_SYS_BOOT
    - CAP_SYS_CHROOT
    - CAP_SETGID
    - CAP_SETUID
    - CAP_CHOWN
    - CAP_DAC_OVERRIDE
    - CAP_DAC_READ_SEARCH
    - CAP_KILL
    - CAP_SYS_TTY_CONFIG
  rootfsPropagation: shared
  net: new
  ipc: new
