name: pkgs publish
on:
  release:
    types:
      - created
jobs:
  push_to_registry:
    name: build linuxkit package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Istall linuxkit
        run: mkdir -p build && curl -L -o build/linuxkit https://github.com/linuxkit/linuxkit/releases/download/v0.8/linuxkit-linux-amd64 && chmod +x build/linuxkit
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Packages
        run: |
           build/linuxkit pkg push -disable-content-trust -network -org jclab pkg/securekit-sftpd
           build/linuxkit pkg push -disable-content-trust -network -org jclab pkg/securekit-disk

